# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      NODE_VERSION: 16.x
      GIT_USER: b-turchyn

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: Configure git credentials
      uses: OleksiyRudenko/gha-git-credentials@v2-latest
      with:
        name: '[ci] Brian Turchyn'
        email: '${{ secrets.GH_USER }}'
        actor: 'b-turchyn'
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Build and Deploy
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USER }}"
        ./src/bin/loc.sh
        npm run deploy
